services:
  app:
    image: scottgal/mostlylucid-pagingtaghelper-sample:latest  # Pulls latest automatically
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_RUNNING_IN_CONTAINER=true
      - ASPNETCORE_URLS=http://+:8080
    networks:
      - app_network

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}  # Store in .env file
    networks:
      - app_network

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    environment:
      - WATCHTOWER_CLEANUP=true       # Remove old images
      - WATCHTOWER_POLL_INTERVAL=3600 # Check every hour (adjust as needed)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
