//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mostlylucid.pagingtaghelper.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PagingResources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PagingResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("mostlylucid.pagingtaghelper.Resources.PagingResources", typeof(PagingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to «.
        /// </summary>
        public static string FirstPageText {
            get {
                return ResourceManager.GetString("FirstPageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ».
        /// </summary>
        public static string LastPageText {
            get {
                return ResourceManager.GetString("LastPageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to go to next page.
        /// </summary>
        public static string NextPageAriaLabel {
            get {
                return ResourceManager.GetString("NextPageAriaLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next ›.
        /// </summary>
        public static string NextPageText {
            get {
                return ResourceManager.GetString("NextPageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page size:.
        /// </summary>
        public static string PageSizeLabel {
            get {
                return ResourceManager.GetString("PageSizeLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1} (Total items: {2}).
        /// </summary>
        public static string PageSummaryFormat {
            get {
                return ResourceManager.GetString("PageSummaryFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ‹ Previous.
        /// </summary>
        public static string PreviousPageText {
            get {
                return ResourceManager.GetString("PreviousPageText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string SkipBackText {
            get {
                return ResourceManager.GetString("SkipBackText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ...
        /// </summary>
        public static string SkipForwardText {
            get {
                return ResourceManager.GetString("SkipForwardText", resourceCulture);
            }
        }
    }
}
